services:
  - type: web
    name: fellasapp
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn --worker-class geventwebsocket.gunicorn.workers.GeventWebSocketWorker --workers 1 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.18
      - key: PORT
        value: 5000
